#!/bin/bash -e

docker run \
    --cidfile=cid \
    -e VERSION=$VERSION \
    -e SHA=$SHA \
    -v $PWD:/go/src/github.com/etcd-io/zetcd:ro \
    -w /go/src/github.com/etcd-io/zetcd \
    golang:1.10.2-alpine \
    /bin/sh -x -c scripts/release-binary

docker cp $( cat cid ):/go/bin/zetcd bin/zetcd-release
docker rm $( cat cid )
rm cid
