#!/bin/sh

REPO_PATH=github.com/coreos/zetcd

go build -o $GOPATH/bin/zetcd -v \
  -ldflags "-w -X $REPO_PATH/version.Version=$VERSION -X $REPO_PATH/version.SHA=$SHA" \
  $REPO_PATH/cmd/zetcd

go build -o $GOPATH/bin/zkctl -v \
  -ldflags "-w -X $REPO_PATH/version.Version=$VERSION -X $REPO_PATH/version.SHA=$SHA" \
  $REPO_PATH/cmd/zkctl
